# Site settings
title: Sparkpipe
email: info@uncharted.software
description: > # this means to ignore newlines until "baseurl:"
  Modular, non-linear pipeline framework for Spark
baseurl: "/sparkpipe-core/" # the subpath of your site, e.g. /blog/
url: "//unchartedsoftware.github.io" # the base hostname & protocol for your site
latest: "1.1.0"

# Build settings
markdown: kramdown
highlighter: rouge

syntax-highlighting:
  enabled : true
  css: syntax.css
